const assert=require('assert');
const fs=require('fs');
const html=fs.readFileSync('index.html','utf8');
const app=fs.readFileSync('app.js','utf8');
const css=fs.readFileSync('styles.css','utf8');
const pkg=require('../package.json');
assert.equal(pkg.version,'34.0.1');
assert.match(html,/Version 34/);
for(const id of ['plateAppearancesViewBtn','currentScorecardViewBtn','plateAppearancesView','currentScorecardView','currentScorecardPreview']) assert(html.includes(`id="${id}"`),`missing ${id}`);
assert.match(app,/const VERSION_NUMBER = 34/);
assert.match(app,/function setScoringView\(/);
assert.match(app,/function renderCurrentScorecardPreview\(/);
assert.match(app,/function completedHalfInningEndingPlays\(/);
assert.match(app,/half-inning-ending-cell/);
assert.match(app,/scoringView:typeof scoringViewMode/);
assert.match(css,/Version 32: Plate Appearances \/ Current Scorecard toggle/);
assert.match(css,/\.half-inning-ending-cell/);
assert.match(css,/inset 0 -4px 0 var\(--brown\)/);
console.log('Version 32 scorecard toggle and half-inning divider checks passed.');
